### ISSUE TITLE
请教人体动作预测

### ISSUE THREAD

**Issue by Tong-Hao741** [eanson023/teslam#1]
学长您好，看到您最近在IEEE上发布的TFAN: Twin-Flow Axis Normalization for Human Motion Prediction论文，感觉很有趣，我刚接触这个任务，想学习代码以及复现，请问何时公开源码呢？

**Comment by eanson023** [comment]
Hi @Tong-Hao741 ,

Please check this [repository](https://github.com/Deante-dx/TFAN), this is the code for TFAN.

**Comment by Tong-Hao741** [comment]
十分感谢！

**Comment by Tong-Hao741** [comment]
十分感谢！
